---
title: "Marks Portfolio"
author: "mark tharakan"
date: "30/07/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

library(igraph)
library(netrankr)



library(tidygraph)


library(ggraph)
library(graphlayouts)



library(osmplotr)
library(ggplot2)
library(prettymapr)
library(sf)

```


```{r}
diamonds
```


```{r}
ggplot(diamonds) +
  geom_point(aes(x = depth,
                 y = price,
                 color = cut),
             size = 0.4)
   ggtitle("Depth")
```

```{r}
bbox_bom <- searchbbox("Mumbai")

dat_b <- extract_osm_objects(bbox = bbox_bom, key = "building")

dat_h <- extract_osm_objects(bbox = bbox_bom, key = "highway")

dat_r <- extract_osm_objects(bbox_bom, key = "amenity", value = "restaurant", return_type = "point")

dat_r <- dat_r %>% drop_na(cuisine)

ggplot() +
  geom_sf(data = dat_b, fill = "blue") +
  geom_sf(data = dat_h, color = "orange" ) +
  geom_sf(data = dat_r, color = "black", fill = "red", size = 1) +
  theme_dark() +
  labs(title = "Mumbai", subtitle = "Taste kahaan hai?")
```


```{r}
naruto_edges <- read_csv("./Data/naruto-edges2.csv")
naruto_nodes <- read.csv("./Data/naruto-nodes.csv")
naruto_nodes
naruto_edges


ns <- tbl_graph(nodes = naruto_nodes,
                edges = naruto_edges,
                directed = FALSE)







ggraph(graph = ns, layout = "kk") +
       geom_edge_link(aes(width = Weight)) +
  geom_node_point(aes(fill = Village),
    shape = 21, size = 6,
                  
                  
                  ) +
  labs(title = "Naruto") +
  geom_node_label(aes(label = Name),
                  repel = TRUE,
                  max.overlaps = 20,
                  size = 3,
                  alpha = 0.6
                  ) 
   
```


